### ISSUE TITLE
add social logins supported swiper to auth server project page

### ISSUE THREAD

**Issue by furknyavuz** [open-template-hub/company-profile-ui-template#116]
<p align="center"><a href="https://opentemplatehub.com"><img src="https://raw.githubusercontent.com/open-template-hub/open-template-hub.github.io/master/assets/logo/brand-logo-merge.gif" alt="Logo" width=150></a></p>
<h2 align="center">Open Template Hub - Feature Request</h2>

### Description

I implemented something similar in my mind just as an inspiration please use the code below to continue.
Please also create a new component for this extending version of swiper-wrapper component

### Supplementary Info

swiper-wrapper-component.html

``` html
<swiper
    [slidesPerView]="1"
    [spaceBetween]="10"
    [loop]="true"
    [autoplay]="{
      delay: 2500,
      disableOnInteraction: false
    }"
    [loopFillGroupWithBlank]="true"
    [pagination]="isPaginationEnabled ? {
      clickable: true
    } : undefined"
    [navigation]="isNavigationEnabled"
    [breakpoints]="breakpoints">
  <ng-template *ngFor="let partner of partners" swiperSlide>
    <img [src]="partner.brandLogo" alt="logo" class="brand-logo " [class.grayscale]="isGrayscale" height="90"/>
  </ng-template>
</swiper>
```

swiper-wrapper-component.scss

``` css
@use '../../../../../node_modules/swiper/swiper-bundle.min.css';

app-swiper-wrapper {
  width: 65%;
  margin: 0 auto;
  position: relative;
}

.swiper {
  width: 100%;
  height: 100%;
  position: initial;
}

.swiper-slide {
  text-align: center;
  font-size: 18px;
  background: transparent;

  /* Center slide text vertically */
  display: -webkit-box;
  display: -ms-flexbox;
  display: -webkit-flex;
  display: flex;
  -webkit-box-pack: center;
  -ms-flex-pack: center;
  -webkit-justify-content: center;
  justify-content: center;
  -webkit-box-align: center;
  -ms-flex-align: center;
  -webkit-align-items: center;
  align-items: center;
}

.swiper-slide img {
  display: block;
  object-fit: cover;

  &.grayscale {
    filter: contrast(0);
  }
}

.swiper-button-prev {
  left: -40px;
}

.swiper-button-next {
  right: -40px;
}

.swiper-button-next, .swiper-button-prev {
  color: var(--contrast);
}

.swiper-button-next::after, .swiper-button-prev::after {
  font-size: 20px;
}

.swiper-pagination-bullet-active {
  background: var(--theme-color);
}

/*
@media only screen and (max-width: 999px) {
  .swiper-button-next::after, .swiper-button-prev::after {
    display: none;
  }
}*/
```

swiper-wrapper-component.ts

``` typescript
import { Component, Input, ViewEncapsulation } from '@angular/core';
import SwiperCore, { Autoplay, Navigation, Pagination } from 'swiper';
import { Partner } from '../../../model/partner/partner.model';

SwiperCore.use( [ Pagination, Navigation, Autoplay ] );

@Component( {
  selector: 'app-swiper-wrapper',
  templateUrl: './swiper-wrapper.component.html',
  styleUrls: [ './swiper-wrapper.component.scss' ],
  encapsulation: ViewEncapsulation.None,
} )

export class SwiperWrapperComponent {
  @Input() partners: Partner[] = [];
  @Input() isNavigationEnabled = false;
  @Input() isPaginationEnabled = false;
  @Input() isGrayscale = false;
  @Input() breakpoints: any = {};
}
```

home.component.html
```html
...
  <app-swiper-wrapper [partners]="PARTNERS" [isGrayscale]="true" [isNavigationEnabled]="true"
                      [isPaginationEnabled]="true" [breakpoints]="{
      '640': {
        slidesPerView: 1,
        spaceBetween: 30
      },
      '768': {
        slidesPerView: 2,
        spaceBetween: 40
      },
      '1200': {
        slidesPerView: 4,
        spaceBetween: 50
      }
      }">
  </app-swiper-wrapper>
  <div class="auth-server-social-login-wrapper">
    <h5>Social logins supported</h5>
    <h6>(and any other OAuth1 and OAuth2 supporting apps and websites)</h6>
    <div class="social-login-wrapper">
      <img [src]="brand.brandLogo" alt="logo" class="brand-logo" width="100"/>
      <i aria-hidden="true" class="fa fa-check-circle success-text"></i>
      <app-swiper-wrapper [partners]="SOCIAL_LOGIN_PARTNERS"></app-swiper-wrapper>
    </div>
  </div>
...
```

home.component.scss
```css
...
.auth-server-social-login-wrapper {
  padding: 5vh 0;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}

.social-login-wrapper {
  padding-top: 2vh;
  width: 350px;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;

  & .brand-logo {
    margin: 0 auto;
  }
}

.social-login-wrapper app-swiper-wrapper {
  height: 100px;
  width: 100px;
}
...
```

home.component.ts
```typescript
...
  SOCIAL_LOGIN_PARTNERS: Partner[] = [];
  constructor(
    private formBuilder: FormBuilder,
    public router: Router,
    private authenticationService: AuthenticationService,
    private themeService: ThemeService,
    private npmProviderService: NpmProviderService
  ) {
    for ( const website in environmentCommon.website ) {
      // filter only oauth configured websites
      if ( environmentCommon.website[ website ].tag && environmentCommon.website[ website ].logo ) {
        console.log( environmentCommon.website[ website ].logo );
        this.SOCIAL_LOGIN_PARTNERS.push({ brandLogo: environmentCommon.website[ website ].logo });
      }
    }
...
```

<table align="right"><tr><td><a href="https://opentemplatehub.com"><img src="https://raw.githubusercontent.com/open-template-hub/open-template-hub.github.io/master/assets/logo/brand-logo.png" width="50px" alt="oth"/></a></td><td><b>Open Template Hub © 2021</b></td></tr></table>
